### ISSUE TITLE
Typo in Lab Manual for CH.6A

### ISSUE THREAD

**Issue by flowersnlyrics** [cypresssemiconductorco/CypressAcademy_BT101_Files#2]
[Chapter 6A](Labmanual/WBT101-06A-ClassicBluetooth-Basic.pdf) PDF typo 

In step 1 on the last exercise it should read ch06a_ex0**3**_spp_mult based on your templates folder. Currently it reads ch06a_ex0**4**_spp_mult

**Comment by greglandry** [comment]
Thanks. I have fixed the instructions.
